### ISSUE TITLE
[STRI 4] Upload payment remainder lost

### ISSUE THREAD

**Issue by C0x41lch0x41** [stellar/stellar-turrets#5]
### What version are you using?
0.0.0

### Scenario
Turrets keeps the total amount of XML sent as payment to upload a contract.

### Why
There is no check to verify that the payment is greater than the cost: https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/txFunctions/upload.js#L41

### Recommendation
We should check that the Fee is equal to the cost.

**Comment by silence48** [comment]
This issue is resolved in ff01c75

The turrets-api will return the exact cost required to upload said contract code.  
ProcessFeePayment can take 4 inputs, env, txfunctionfee, min, max.
https://github.com/stellar/stellar-turrets/blob/ff01c750d6704d8a11a5cd11d5d63b0dc7eb2017/wrangler/src/%40utils/stellar-sdk-utils.js#L93
https://github.com/stellar/stellar-turrets/blob/ff01c750d6704d8a11a5cd11d5d63b0dc7eb2017/wrangler/src/%40utils/stellar-sdk-utils.js#L108-L118
The fix is almost unnoticable as we just need to pass the max param to be the same as the min param.  I utilized the max to require the exact cost to be included in the txFunctionFee
https://github.com/stellar/stellar-turrets/blob/ff01c750d6704d8a11a5cd11d5d63b0dc7eb2017/wrangler/src/txFunctions/upload.js#L46
Specifically the user should attempt an upload not knowing the cost, and get the cost through this attempt.

**Comment by C0x41lch0x41** [comment]
This is patched here: https://github.com/stellar/stellar-turrets/pull/11 and merged into master here: https://github.com/stellar/stellar-turrets/commit/cf6de0e32adfd2e6f1ff73a8eaa8e8cce9de00de
